### ISSUE TITLE
urllib2.HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by jc-ren** [pyne/install_scripts#25]
after running"./ubuntu_16.04.sh stable”，report an error:
File "/usr/local/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: SSL is required

how to fix this problem?
thank you!

**Comment by kkiesling** [comment]
Hi @renjincai - can you provide the full output for this error? What line does the error occur at? Thanks!

**Comment by renjincai** [comment]
> 
> 
> Hi @renjincai - can you provide the full output for this error? What line in the bash script does the error occur at? Thanks!

sorry,that problem has disappeared .
my system is ubuntu14.04,and i used the command "./ubuntu_16.04.sh stable"to install pyne .
but it reported errors as follows:

……
PyTAPS-1.4/common.h
Couldn't find index page for 'numpy' (maybe misspelled?)
No local packages or download links found for numpy>=1.3.0
Traceback (most recent call last):
  File "setup.py", line 476, in <module>
    zip_safe = False,
  File "/usr/local/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/dist.py", line 260, in __init__
  File "/usr/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/dist.py", line 284, in fetch_build_eggs
  File "/usr/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 563, in resolve
  File "/usr/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 799, in best_match
  File "/usr/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 811, in obtain
  File "/usr/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/dist.py", line 327, in fetch_build_egg
  File "/usr/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 434, in easy_install
  File "/usr/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/package_index.py", line 475, in fetch_distribution
AttributeError: 'NoneType' object has no attribute 'clone'

Can anyone help me fix the problem?thank you!

**Comment by renjincai** [comment]
Then I  used the command "./ubuntu_16.04.sh stable"to install pyne .
but it reported errors as follows:

……
Fetching pre-built nuc_data.h5 from http://data.pyne.io/prebuilt_nuc_data.h5
Traceback (most recent call last):
  File "./scripts/nuc_data_make", line 6, in <module>
    main()
  File "/root/.local/lib/python2.7/site-packages/pyne/dbgen/nuc_data_make.py", line 152, in main
    _fetch_prebuilt(args)
  File "/root/.local/lib/python2.7/site-packages/pyne/dbgen/nuc_data_make.py", line 71, in _fetch_prebuilt
    pnd = urllib2.urlopen(prebuilt_nuc_data_url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

Could anyone help me to fix this one?thank you!

**Comment by Mongwell** [comment]
It seems http://data.pyne.io no longer exists. Newer releases as well as the develop branch of PyNE now fetch the pre-built data from https://github.com/pyne/data/raw/master/prebuilt_nuc_data.h5 . Using the install script with 'stable' will now obtain the newer release. This should no longer be an issue?

**Comment by gonuke** [comment]
I'm not sure if all the data has been moved to github.com/pyne/data - this would be a good outcome from this issue.

**Comment by kkiesling** [comment]
has this issue been resolved with the latest updates to data and the newest release?

**Comment by bam241** [comment]
this should not be a problem anymore.
Closing!
Feel free to reopen if the issue raises again in the future.
