### ISSUE TITLE
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

### ISSUE THREAD

**Issue by AsmaFarhat** [pyne/install_scripts#67]
**When I try to run :  npm run serve --port3000, I get these errors:**

```
sh: vue-cli-service: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! test_web@0.1.0 serve: `vue-cli-service serve`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the test_web@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2022-06-20T13_49_46_276Z-debug.log

```

**Debug log :** 
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/user/.nvm/versions/node/v14.16.1/bin/node',
1 verbose cli   '/home/user/.nvm/versions/node/v14.16.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'serve',
1 verbose cli   '--port3000'
1 verbose cli ]
2 info using npm@6.14.12
3 info using node@v14.16.1
4 verbose run-script [ 'preserve', 'serve', 'postserve' ]
5 info lifecycle test_web@0.1.0~preserve: test_web@0.1.0
6 info lifecycle test_web@0.1.0~serve: test_web@0.1.0
7 verbose lifecycle test_web@0.1.0~serve: unsafe-perm in lifecycle true
8 verbose lifecycle test_web@0.1.0~serve: PATH: /home/user/.nvm/versions/node/v14.16.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/user/Bureau/tool/node_modules/.bin:/home/.nvm/versions/node/v14.16.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/puppetlabs/bin
9 verbose lifecycle test_web@0.1.0~serve: CWD: /home/user/Bureau/tool
10 silly lifecycle test_web@0.1.0~serve: Args: [ '-c', 'vue-cli-service serve' ]
11 info lifecycle test_web@0.1.0~serve: Failed to exec serve script
12 verbose stack Error: test_web@0.1.0 serve: `vue-cli-service serve`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/home/user/.nvm/versions/node/v14.16.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:315:20)
12 verbose stack     at maybeClose (internal/child_process.js:1048:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
13 verbose pkgid test_web@0.1.0
14 verbose cwd /home/user/Bureau/tool
15 verbose Linux 5.4.0-120-generic
16 verbose argv "/home/.nvm/versions/node/v14.16.1/bin/node" "/home/user/.nvm/versions/node/v14.16.1/bin/npm" "run" "serve" "--port3000"
17 verbose node v14.16.1
18 verbose npm  v6.14.12
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error test_web@0.1.0 serve: `vue-cli-service serve`
23 error spawn ENOENT
24 error Failed at the test_web@0.1.0 serve script.
24 error This is probably not a problem with npm. There is likely additional logging output above.

```

**pakage.json : ** 
```
{
  "name": "test_web",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@popperjs/core": "^2.9.2",
    "core-js": "^3.6.5",
    "file-saver": "^2.0.5",
    "raw-loader": "^4.0.2",
    "sqlite3": "^5.0.2",
    "vue": "^3.0.0",
    "vue-router": "^4.0.6"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "babel-eslint": "^10.1.0",
    "bootstrap": "^5.0.1",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0",
    "jquery": "^3.6.0",
    "popper.js": "^1.16.1"
  }
```
**Can someone tell me what I'm doing wrong?**

**Comment by bam241** [comment]
Hello,

thank you for your question.

Unfortunately I am unsure of what you are trying to accomplish, therefore it is difficult to help you.

Maybe you should start by stating precisely what you are trying to accomplish with the PyNE install_scripts, describing precisely your system.

BaM

**Comment by AsmaFarhat** [comment]
Hi BaM , thanks for your answer.
I'm trying to run a website application at port 3000 for testing , this website will extract data from a local database,

**Comment by bam241** [comment]
Is this correlated to any of the PyNE instal_scripts ?

If not you should check directly with he github help pages...

**Comment by AsmaFarhat** [comment]
OK I understand. 
Could you tell me where is the right place to ask please !
